## Table Extraction

In [17]:
!pip install pandas
!pip install lxml

Requirement already satisfied: pandas in /home/crs/ai-lab/lib/python3.10/site-packages (2.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/crs/ai-lab/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: numpy>=1.22.4 in /home/crs/ai-lab/lib/python3.10/site-packages (from pandas) (1.26.4)
Requirement already satisfied: tzdata>=2022.7 in /home/crs/ai-lab/lib/python3.10/site-packages (from pandas) (2024.2)
Requirement already satisfied: pytz>=2020.1 in /home/crs/ai-lab/lib/python3.10/site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /home/crs/ai-lab/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: lxml in /home/crs/ai-lab/lib/python3.10/site-packages (5.3.0)

In [25]:
import pandas as pd
import os, sys 

# Construct the full path to the Scripts folder
scripts_dir = os.path.join("../Scripts/")
# Append the directory of the module to sys.path 
sys.path.append(scripts_dir)
# sys.path.append(os.path.join("../Scripts"))

# from DataExtractionFromWebsite import DataExtractionFromWebsite
from Scripts.DataExtractionFromWebsite import DataExtractionFromWebsite


web_extraction = DataExtractionFromWebsite()

#### Extraction of Table from a website

Target website: https://en.wikipedia.org/wiki/List_of_The_Simpsons_episodes_(seasons_1%E2%80%9320)

In [26]:
# Extraction from website using pandas library
tables_data = web_extraction.tablesExtraction("https://en.wikipedia.org/wiki/List_of_The_Simpsons_episodes_(seasons_1%E2%80%9320)")

In [27]:
# length of the list
len(tables_data)

24

In [28]:
# Display the first episode on the website
tables_data[1]

,No. overall,No. in season,Title,Directed by,Written by,Original air date,Prod. code,U.S. viewers (millions)
0,1,1,"""Simpsons Roasting on an Open Fire""",David Silverman,Mimi Pond,"December 17, 1989[47]",7G08,26.7[48]
1,2,2,"""Bart the Genius""",David Silverman,Jon Vitti,"January 14, 1990[49]",7G02,24.5[48]
2,3,3,"""Homer's Odyssey""",Wes Archer,Jay Kogen & Wallace Wolodarsky,"January 21, 1990[50]",7G03,27.5[51]
3,4,4,"""There's No Disgrace Like Home""",Gregg Vanzo & Kent Butterworth,Al Jean & Mike Reiss,"January 28, 1990[52]",7G04,20.2[53]
4,5,5,"""Bart the General""",David Silverman,John Swartzwelder,"February 4, 1990[54]",7G05,27.1[55]
5,6,6,"""Moaning Lisa""",Wes Archer,Al Jean & Mike Reiss,"February 11, 1990[56]",7G06,27.4[57]
6,7,7,"""The Call of the Simpsons""",Wes Archer,John Swartzwelder,"February 18, 1990[58]",7G09,27.6[59]
7,8,8,"""The Telltale Head""",Rich Moore,"Al Jean, Mike Reiss, Sam Simon & Matt Groening","February 25, 1990[60]",7G07,28.0[61]
8,9,9,"""Life on the Fast Lane""",David Silverman,John Swartzwelder,"March 18, 1990[62]",7G11,33.5[63]
9,10,10,"""Homer's Night Out""",Rich Moore,Jon Vitti,"March 25, 1990[64]",7G10,30.3[65]
10,11,11,"""The Crepes of Wrath""",Wes Archer & Milton Gray,"George Meyer, Sam Simon, John Swartzwelder & J...","April 15, 1990[66]",7G13,31.2[67]
11,12,12,"""Krusty Gets Busted""",Brad Bird,Jay Kogen & Wallace Wolodarsky,"April 29, 1990[68]",7G12,30.4[69]
12,13,13,"""Some Enchanted Evening""",David Silverman & Kent Butterworth,Matt Groening & Sam Simon,"May 13, 1990[70]",7G01,27.1[71]

#### Read a .csv from a URL with Pandas

Target website: https://www.football-data.co.uk/data.php

In [29]:
# Extract 1 .csv file from the webside
csv_data_premier24 = web_extraction.csvFilesExtraction("https://www.football-data.co.uk/mmz4281/2425/E0.csv")
csv_data_premier24

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.90,2.08
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2.05,1.88,2.04,1.90,2.20,2.00,1.99,1.88,2.04,1.93
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,2.02,1.91,2.00,1.90,2.05,1.93,1.99,1.87,2.02,1.96
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1.87,2.06,1.88,2.06,1.89,2.10,1.82,2.05,1.89,2.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,E0,30/11/2024,17:30,West Ham,Arsenal,2,5,A,2,5,...,1.92,1.98,1.94,1.98,1.95,2.02,1.90,1.96,1.98,2.01
126,E0,01/12/2024,13:30,Chelsea,Aston Villa,3,0,H,2,0,...,1.97,1.96,1.96,1.96,1.99,2.03,1.90,1.96,1.93,2.04
127,E0,01/12/2024,13:30,Man United,Everton,4,0,H,2,0,...,2.05,1.88,2.07,1.86,2.17,1.90,2.05,1.83,2.06,1.92
128,E0,01/12/2024,13:30,Tottenham,Fulham,1,1,D,0,0,...,2.00,1.93,1.99,1.93,2.00,1.96,1.95,1.91,1.99,2.00
129,E0,01/12/2024,16:00,Liverpool,Man City,2,0,H,1,0,...,2.07,1.86,2.07,1.86,2.08,1.89,2.03,1.84,2.10,1.89

In [30]:
# Rename colums
csv_data_premier24.rename(columns={"FTHG": "home_goals", 
                                   "FTAG": "away_goals"}, inplace = True)

In [31]:
# Show dataframe
csv_data_premier24

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.90,2.08
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2.05,1.88,2.04,1.90,2.20,2.00,1.99,1.88,2.04,1.93
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,2.02,1.91,2.00,1.90,2.05,1.93,1.99,1.87,2.02,1.96
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1.87,2.06,1.88,2.06,1.89,2.10,1.82,2.05,1.89,2.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,E0,30/11/2024,17:30,West Ham,Arsenal,2,5,A,2,5,...,1.92,1.98,1.94,1.98,1.95,2.02,1.90,1.96,1.98,2.01
126,E0,01/12/2024,13:30,Chelsea,Aston Villa,3,0,H,2,0,...,1.97,1.96,1.96,1.96,1.99,2.03,1.90,1.96,1.93,2.04
127,E0,01/12/2024,13:30,Man United,Everton,4,0,H,2,0,...,2.05,1.88,2.07,1.86,2.17,1.90,2.05,1.83,2.06,1.92
128,E0,01/12/2024,13:30,Tottenham,Fulham,1,1,D,0,0,...,2.00,1.93,1.99,1.93,2.00,1.96,1.95,1.91,1.99,2.00
129,E0,01/12/2024,16:00,Liverpool,Man City,2,0,H,1,0,...,2.07,1.86,2.07,1.86,2.08,1.89,2.03,1.84,2.10,1.89

#### Extraction tables from PDF

Install camelot-py to extract tables from PDF

In [40]:
# # !pip install camelot-py
# import camelot

# tables = camelot.read_pdf("foo.pdf", pages=1)
# print(tables)
# tables.export("foo.csv", f="csv", compress= True)
# tables[0].to_csv("foo.csv")

## Web Automation & Web Scraping: HTML - Tags

### HTML Tags & Elements
- h1 : Tag name
- class = "title" : Attribute
- Homepage : Affected content  
- /h1 : End Tag

#### Web Scraping: Xpath - Syntax
- `//tagName`
- `//tagName[1]`
- `//tagName[@AttributeName="Value"]`       This is the standard syntax

#### Xpath functions
- `contains()`
- `starts-with()`

#### Updated Xpath Syntax
- `//tagName[contains(@AttributeName, "Value")]`

#### Xpath Operators
- `and `
- `or`
- Xpath Syntax : `//tagName[(expression 1) and (expression 2)]`

#### Xpath - Testing Xpath
- Go to: scrapinghub.github.io/xpath-playground/

#### Xpath - Special character
- `/`: Select the children from the node set on the left side of this character

- `//`: Specifies that the matching node set should be located at any level within the document.

- **Note**: if you want the text use `/text()`

- `.`: Specifies the current context should be used (refers to present node)

- `..`: Refers to a parent node

- `*`: A wildcard character that selects all elements or attributes regardless of names

- `./*`: Select all the children nodes considering the current context

- `@`: Select an attribute

- `()`: Grouping an XPath expression

- `[n]`: Inddicates that a node with index 'n' should be selected